export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_PENDING = 'GET_POSTS_PENDING';
export const GET_POSTS_FULFILLED = 'GET_POSTS_FULFILLED';
export const GET_POSTS_REJECTED = 'GET_POSTS_REJECTED';

export const GET_POST_BY_ID = 'GET_POST_BY_ID';
export const GET_POST_BY_ID_PENDING = 'GET_POST_BY_ID_PENDING';
export const GET_POST_BY_ID_FULFILLED = 'GET_POST_BY_ID_FULFILLED';
export const GET_POST_BY_ID_REJECTED = 'GET_POST_BY_ID_REJECTED';

export const ADD_POST = 'ADD_POST';
export const ADD_POST_PENDING = 'ADD_POST_PENDING';
export const ADD_POST_FULFILLED = 'ADD_POST_FULFILLED';
export const ADD_POST_REJECTED = 'ADD_POST_REJECTED';

export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_PENDING = 'EDIT_POST_PENDING';
export const EDIT_POST_FULFILLED = 'EDIT_POST_FULFILLED';
export const EDIT_POST_REJECTED = 'EDIT_POST_REJECTED';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_PENDING = 'DELETE_POST_PENDING';
export const DELETE_POST_FULFILLED = 'DELETE_POST_FULFILLED';
export const DELETE_POST_REJECTED = 'DELETE_POST_REJECTED';